name: Selenium Course Browser Tests

on:
  workflow_dispatch:

  #pull_request:
  #  branches: [ "main" ]

jobs:
  chrome-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests

      - name: Run headless in Github
        run: |
          echo "in github" > runInGithub.txt  
          ls -al
        shell: bash

      - name: Run Regression
        run: mvn clean test -Dbrowser=chrome

  firefox-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests

      - name: Run headless in Github
        run: |
          echo "in github" > runInGithub.txt  
          ls -al
        shell: bash

      - name: Run Regression
        run: mvn clean test -Dbrowser=firefox
